# Generated by Django 2.1.1 on 2019-12-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('LO', 'LORRYOWNER'), ('DA', 'DRIVER')], default='NU', max_length=2),
        ),
    ]
