# Generated by Django 2.1.1 on 2019-12-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_registerdriver_referedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('LO', 'LORRYOWNER'), ('DA', 'DRIVER'), ('AO', 'APPLICATION_OWNER'), ('MA', 'MANAGER'), ('NU', 'NORMALUSER')], default='NU', max_length=2),
        ),
    ]
